name = "car-library-api"
main = "src/index.ts"
compatibility_date = "2024-03-01"

# Secrets (set via `wrangler secret put`):
#   JWT_SECRET

[[d1_databases]]
binding = "DB"
database_name = "car-library-db"
database_id = "aee377bf-50f4-45c5-881e-ad86222f8d6d"

[[r2_buckets]]
binding = "CAR_IMAGES"
bucket_name = "car-images"

[ai]
binding = "AI"
